name: amcts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - jupyter
  - notebook
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - networkx
  - scipy
  - tqdm
  - nbstripout
  - graphviz
  - pydot
  - nbdime
  - folium
  - flask
  - werkzeug
  - pip
  - pip:
    - gunicorn==22.0.0